apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: {{ .Values.email.production }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: production-account-key
    solvers:
    - http01:
        ingress:
          class: nginx