apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
      matchLabels:
        tier: database
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}